### ISSUE TITLE
IamIdentityV1 list_service_ids() Returns URL instead of Token for Next Page

### ISSUE THREAD

**Issue by bparrill** [IBM/platform-services-python-sdk#114]
This may not necessarily be a bug, but the `list_service_ids()` function in `IamIdentityV1 ` has a parameter for `pagetoken` in order to get different pages of output.
However, when calling the function it returns `previous` and `next` values in the form of a URL, which the `pagetoken` cannot use directly.
While it's easy enough to parse the the URL to get the token, it would help simplify application code if `previous` and `next` were returned as `pagetoken` compatible strings rather than URLS.

**Comment by padamstx** [comment]
cc: @pooraniss-ibm

**Comment by padamstx** [comment]
@bparrill I think the IBM Identity service (like a lot of IBM Cloud services) returns the "prev" and "next" values as URLs because that was perhaps more convenient for non-SDK users (e.g. users that might use curl to invoke the operations, or perhaps use a programming language without the high-level functionality provided by the SDKs).   Ideally, the service could return both the next/prev URL strings and also the next/prev pagetoken values.  That way both constituencies could be served.

However, it turns out that the Python core library (a dependency of the Python SDK) contains a function that can retrieve the query param value from the next/prev URLnamed `get_query_param()`

Here's an example of how to use it:
```
from ibm_cloud_sdk_core import *

...

# assume "next_url" contains the "next" url value obtained from a list-type response.
page_token = get_query_param(next_url, 'pagetoken')
...
```

Also, another example of this can be found here:
https://github.com/IBM/platform-services-python-sdk/blob/db035b4d3a520e1ffd31251885b9e8a34d3bd97b/test/integration/test_resource_controller_v2.py#L218

Hope this helps.
