### ISSUE TITLE
All examples should include pagination

### ISSUE THREAD

**Issue by data-henrik** [IBM/platform-services-python-sdk#161]
To simplify usage, all provided code samples should include pagination (and error handling). Basically, the samples should demonstrate best practices.

**Comment by padamstx** [comment]
Hi @data-henrik, thanks for your suggestions.   It turns out that we have recently delivered a new feature in the SDK generator (which is used to generate the code packaged in IBM Cloud SDKs) where we now have the ability to generate examples that do in fact demonstrate pagination for list-type operations that support it.   It will, however, take some time before the services are updated within the various SDKs such that their examples reflect this.   I'll leave this issue open for now...
